# Generated by matugen — do not edit
export M_BACKGROUND=#0f1416
export M_ON_BACKGROUND=#dee3e6
export M_PRIMARY=#85d2e8
export M_ON_PRIMARY=#003641
export M_SECONDARY=#b2cbd3
export M_TERTIARY=#bfc4eb
export M_SURFACE=#0f1416
export M_ON_SURFACE=#dee3e6
export M_SURFACE_VARIANT=#3f484b
export M_ON_SURFACE_VARIANT=#bfc8cb
export M_ERROR=#ffb4ab
export M_OUTLINE=#899295

